version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "gomod"
  directory: "/tests/integration/"
  schedule:
    interval: "weekly"
