language: go

go: 1.14.x

os: linux
dist: bionic

cache:
  directories:
  - ${HOME}/assets
  - ${GOPATH}/pkg/mod
  - ${GOPATH}/bin

jobs:
  include:
  - name: Verify
    stage: verify
    script: make verify
  - name: Lint
    stage: lint
    before_script:
    - GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.3
    script: make lint
  - name: Test
    stage: test
    before_script:
    - go install github.com/onsi/ginkgo/ginkgo
    script: make test-unit
  - name: Integration tests
    stage: test-integration
    services:
    - docker
    env:
    - CHANGE_MINIKUBE_NONE_USER=false
    - MINIKUBE_HOME=${HOME}
    before_install:
    - sudo apt-get -qq -y install conntrack
    before_script:
    - ci/install/integration.sh
    - go install github.com/onsi/ginkgo/ginkgo
    script: ci/test_integration.sh

stages:
- verify
- lint
- test
- test-integration

deploy:
  provider: script
  script: make release
  on:
    repo: kubernetes-sigs/minibroker
    all_branches: true
