language: go

go:
- 1.13.x
- 1.14.x

os: linux
dist: bionic

cache:
  directories:
  - ${HOME}/assets
  - ${GOPATH}/pkg/mod
  - ${GOPATH}/bin

before_install:
- sudo apt-get -qq -y install conntrack

before_script:
- ci/install_tools.sh

services:
- docker

script:
- make build
- make test-unit

jobs:
  include:
  - name: Verify
    stage: verify
    script: make verify
  - name: Lint
    stage: lint
    go: 1.14.x
    script: make lint
  - name: Integration tests
    stage: test-integration
    env:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=${HOME}
    - CHANGE_MINIKUBE_NONE_USER=true
    script: ci/test_integration.sh

stages:
- verify
- lint
- test
- test-integration

deploy:
  provider: script
  script: make release
  on:
    repo: kubernetes-sigs/minibroker
    all_branches: true
